/// <reference types="nativewind/types" />

// Permite importar arquivos .css dentro do TypeScript/React Native (processados pelo Metro + NativeWind)
declare module '*.css';

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.